### ISSUE TITLE
PHP 8.0 or 8.1

### ISSUE THREAD

**Issue by Tofandel** [renovatebot/docker-renovate-full#415]
PHP8 has been around for 1 year and a half now and most framework now requires at least PHP8.0 in their composer.json (eg: symfony, laravel) this makes renovate bot not able to update the composer dependencies anymore with this image which still provides PHP7.4

**Comment by rarkins** [comment]
Use the slim image with Docker socket mapped

**Comment by sveba** [comment]
@rarkins Can you please explain what is the plan about the full image?
In our organization we can not use the slim-image with Docker socket because our build infrastructure is air gaped (we can not just pull everything from the internet)
For this purpose the full image is really useful. The problem is that it is not being updated with the new versions of the tools (maven, gradle, php etc.) 
Here is a list of the CVEs that the current tool versions have (it is long):
 Vulnerabilities:
Critical   CVE-2019-15052   gradle-build-cache-packaging-6.9.2
Critical   CVE-2021-26291   maven-compat-3.0.5
Critical   CVE-2021-29940   through-2.3.8
Critical   CVE-2021-29940   through-2.3.8
Critical   CVE-2022-0543   redis-4.0.6
Critical   CVE-2019-15052   gradle-build-events-6.9.2
Critical   CVE-2021-26291   maven-settings-builder-3.0.5
Critical   GHSA-xvch-5gv4-984h   minimist-1.2.5
Critical   CVE-2019-15052   gradle-build-cache-base-6.9.2
Critical   CVE-2021-26291   maven-settings-3.0.5
Critical   CVE-2020-9493   log4j-over-slf4j-1.7.28
Critical   CVE-2019-15052   gradle-build-option-6.9.2
Critical   GHSA-xvch-5gv4-984h   minimist-1.2.5
Critical   CVE-2021-26291   maven-aether-provider-3.0.5
Critical   CVE-2018-11218   redis-4.0.6
Critical   CVE-2021-26291   maven-model-builder-3.0.5
Critical   CVE-2021-26291   maven-artifact-3.0.5
Critical   CVE-2019-15052   gradle-build-cache-6.9.2
Critical   CVE-2019-15052   gradle-build-operations-6.9.2
Critical   CVE-2021-26291   maven-core-3.0.5
Critical   CVE-2019-15052   gradle-build-profile-6.9.2
Critical   CVE-2021-26291   maven-model-3.0.5
Critical   CVE-2018-11219   redis-4.0.6
Critical   CVE-2019-15052   gradle-build-init-6.9.2
Critical   CVE-2021-26291   maven-repository-metadata-3.0.5
Critical   CVE-2019-15052   gradle-build-cache-http-6.9.2
High   CVE-2021-29428   gradle-build-cache-6.9.2
High   CVE-2018-12326   redis-4.0.6
High   CVE-2021-29428   gradle-build-cache-http-6.9.2
High   CVE-2021-29428   gradle-build-option-6.9.2
High   CVE-2021-32751   gradle-build-cache-http-6.9.2
High   CVE-2020-11979   gradle-build-cache-base-6.9.2
High   CVE-2019-10193   redis-4.0.6
High   CVE-2021-29428   gradle-build-cache-packaging-6.9.2
High   CVE-2021-32751   gradle-build-init-6.9.2
High   CVE-2020-11979   gradle-build-events-6.9.2
High   CVE-2021-29428   gradle-build-operations-6.9.2
High   CVE-2021-32751   gradle-build-cache-base-6.9.2
High   CVE-2020-7712   json-2.6.1
High   CVE-2020-11979   gradle-build-cache-packaging-6.9.2
High   CVE-2021-32626   redis-4.0.6
High   CVE-2020-11979   gradle-build-init-6.9.2
High   CVE-2021-29428   gradle-build-profile-6.9.2
High   GHSA-crv7-7245-f45f   commons-compress-1.19
High   CVE-2021-29428   gradle-build-events-6.9.2
High   CVE-2021-32751   gradle-build-profile-6.9.2
High   CVE-2017-14727   logger-1.5.0
High   CVE-2020-11979   gradle-build-cache-6.9.2
High   CVE-2022-25364   gradle-build-init-6.9.2
High   CVE-2020-11979   gradle-build-option-6.9.2
High   CVE-2015-0903   editor-1.0.0
High   CVE-2005-0861   delegate-0.2.0
High   GHSA-xqfj-vm6h-2x34   commons-compress-1.19
High   CVE-2021-32751   gradle-build-cache-packaging-6.9.2
High   GHSA-mc84-pj99-q6hh   commons-compress-1.19
High   CVE-2021-29428   gradle-build-init-6.9.2
High   CVE-2021-4044   openssl-3.0.0
High   CVE-2022-1015   linux-libc-dev-5.4.0-109.123
High   CVE-2020-11979   gradle-build-cache-http-6.9.2
High   CVE-2021-32751   gradle-build-cache-6.9.2
High   CVE-2020-11979   gradle-build-operations-6.9.2
High   CVE-2008-4318   observer-0.1.1
High   CVE-2020-14147   redis-4.0.6
High   CVE-2022-23307   log4j-over-slf4j-1.7.28
High   GHSA-57j2-w4cx-62h2   jackson-databind-2.12.1
High   CVE-2022-25364   gradle-build-cache-http-6.9.2
High   CVE-2018-12453   redis-4.0.6
High   CVE-2021-32751   gradle-build-operations-6.9.2
High   CVE-2014-1936   rc-1.2.8
High   CVE-2020-7791   i18n-1.10.0
High   CVE-2019-10192   redis-4.0.6
High   CVE-2021-29428   gradle-build-cache-base-6.9.2
High   CVE-2022-25364   gradle-build-events-6.9.2
High   CVE-2020-11979   gradle-build-profile-6.9.2
High   CVE-2022-25364   gradle-build-cache-base-6.9.2
High   CVE-2021-32761   redis-4.0.6
High   CVE-2021-21309   redis-4.0.6
High   CVE-2022-25364   gradle-build-option-6.9.2
High   CVE-2021-32751   gradle-build-option-6.9.2
High   GHSA-7hfm-57qf-j43q   commons-compress-1.19
High   GHSA-qc9x-gjcv-465w   pipenv-2020.11.15
High   CVE-2017-14198   matrix-0.4.2
High   CVE-2022-0778   openssl-3.0.0
High   CVE-2022-25364   gradle-build-cache-packaging-6.9.2
High   CVE-2022-25364   gradle-build-profile-6.9.2
High   CVE-2022-25364   gradle-build-operations-6.9.2
High   CVE-2021-32751   gradle-build-events-6.9.2
High   CVE-2022-25364   gradle-build-cache-6.9.2
Low   CVE-2016-2781   coreutils-8.30-3ubuntu2
Low   CVE-2019-1010204   binutils-common-2.34-6ubuntu1.3
Low   CVE-2019-15213   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-3671   libroken18-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2019-1010204   binutils-2.34-6ubuntu1.3
Low   CVE-2021-3671   libasn1-8-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2015-9019   libxslt1.1-1.1.34-4
Low   CVE-2021-3671   libheimbase1-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2020-17541   libjpeg-turbo8-2.0.3-0ubuntu1.20.04.1
Low   CVE-2021-3671   libhcrypto4-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2020-35501   linux-libc-dev-5.4.0-109.123
Low   CVE-2018-12931   linux-libc-dev-5.4.0-109.123
Low   CVE-2019-1010204   libbinutils-2.34-6ubuntu1.3
Low   CVE-2019-14899   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-36087   libsepol1-3.0-1
Low   CVE-2022-27223   linux-libc-dev-5.4.0-109.123
Low   CVE-2020-14304   linux-libc-dev-5.4.0-109.123
Low   CVE-2017-13716   libctf0-2.34-6ubuntu1.3
Low   CVE-2021-3671   libkrb5-26-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2021-3669   linux-libc-dev-5.4.0-109.123
Low   CVE-2015-20107   libpython2.7-minimal-2.7.18-1~20.04.1
Low   CVE-2021-34981   linux-libc-dev-5.4.0-109.123
Low   CVE-2020-11725   linux-libc-dev-5.4.0-109.123
Low   CVE-2019-20838   libpcre3-2:8.39-12build1
Low   CVE-2015-20107   libpython3.8-minimal-3.8.10-0ubuntu1~20.04.4
Low   CVE-2017-13716   libctf-nobfd0-2.34-6ubuntu1.3
Low   CVE-2018-1000021   git-1:2.36.0-0ppa1~ubuntu20.04.1
Low   CVE-2020-27820   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-36084   libsepol1-3.0-1
Low   CVE-2018-1000021   git-man-1:2.36.0-0ppa1~ubuntu20.04.1
Low   CVE-2015-20107   python2.7-minimal-2.7.18-1~20.04.1
Low   CVE-2013-4235   login-1:4.8.1-1ubuntu5.20.04.1
Low   CVE-2019-1010204   libctf0-2.34-6ubuntu1.3
Low   CVE-2020-14145   openssh-client-1:8.2p1-4ubuntu0.4
Low   CVE-2022-0854   linux-libc-dev-5.4.0-109.123
Low   CVE-2014-2524   readline-0.0.3
Low   CVE-2020-12364   linux-libc-dev-5.4.0-109.123
Low   CVE-2020-9991   libsqlite3-0-3.31.1-4ubuntu0.2
Low   CVE-2018-12930   linux-libc-dev-5.4.0-109.123
Low   GHSA-5mg8-w23w-74h3   guava-27.1-android
Low   CVE-2022-0617   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-3671   libwind0-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2021-36085   libsepol1-3.0-1
Low   CVE-2018-12929   linux-libc-dev-5.4.0-109.123
Low   CVE-2020-12363   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-3671   libgssapi3-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2021-3671   libheimntlm0-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2017-0537   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-41617   openssh-client-1:8.2p1-4ubuntu0.4
Low   CVE-2015-20107   libpython3.8-stdlib-3.8.10-0ubuntu1~20.04.4
Low   CVE-2021-4217   unzip-6.0-25ubuntu1
Low   CVE-2020-9849   libsqlite3-0-3.31.1-4ubuntu0.2
Low   CVE-2015-20107   libpython2.7-stdlib-2.7.18-1~20.04.1
Low   CVE-2019-19814   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-3772   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-3671   libhx509-5-heimdal-7.7.0+dfsg-1ubuntu1
Low   CVE-2015-20107   python3.8-3.8.10-0ubuntu1~20.04.4
Low   CVE-2017-13716   libbinutils-2.34-6ubuntu1.3
Low   CVE-2013-4235   passwd-1:4.8.1-1ubuntu5.20.04.1
Low   CVE-2022-0530   unzip-6.0-25ubuntu1
Low   CVE-2019-18276   bash-5.0-6ubuntu1.1
Low   CVE-2017-13716   binutils-2.34-6ubuntu1.3
Low   CVE-2015-20107   python3.8-minimal-3.8.10-0ubuntu1~20.04.4
Low   CVE-2018-1121   linux-libc-dev-5.4.0-109.123
Low   CVE-2021-36086   libsepol1-3.0-1
Low   CVE-2017-13716   binutils-x86-64-linux-gnu-2.34-6ubuntu1.3
Low   CVE-2021-33503   python3-urllib3-1.25.8-2ubuntu0.1
Low   CVE-2014-5169   date-3.2.2
Low   CVE-2019-1010204   libctf-nobfd0-2.34-6ubuntu1.3
Low   CVE-2021-43618   libgmp10-2:6.2.0+dfsg-4
Low   CVE-2017-13716   binutils-common-2.34-6ubuntu1.3
Low   CVE-2019-19378   linux-libc-dev-5.4.0-109.123
Low   CVE-2015-20107   python2.7-2.7.18-1~20.04.1
Low   CVE-2019-1010204   binutils-x86-64-linux-gnu-2.34-6ubuntu1.3
Medium   CVE-2020-29509   go-1.18.1
Medium   CVE-2021-3894   linux-libc-dev-5.4.0-109.123
Medium   CVE-2019-16370   gradle-build-profile-6.9.2
Medium   CVE-1999-1338   delegate-0.2.0
Medium   CVE-2019-16370   gradle-build-option-6.9.2
Medium   CVE-2020-36310   linux-libc-dev-5.4.0-109.123
Medium   CVE-2007-4559   python-3.10.4
Medium   CVE-2022-0494   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-45469   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-1198   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-25375   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-23040   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-1016   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-1048   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-13844   gcc-9-9.4.0-1ubuntu1~20.04.1
Medium   CVE-2020-13844   g++-4:9.3.0-1ubuntu2
Medium   CVE-2016-8660   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-0480   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-1205   linux-libc-dev-5.4.0-109.123
Medium   GHSA-gwrp-pvrq-jmwv   commons-io-2.6
Medium   CVE-2022-25258   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-29429   gradle-build-init-6.9.2
Medium   CVE-2020-16156   perl-base-5.30.0-9ubuntu0.2
Medium   CVE-2022-0400   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-44879   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-39801   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-13844   cpp-4:9.3.0-1ubuntu2
Medium   GHSA-93q8-gq69-wqmw   ansi-regex-4.1.0
Medium   CVE-2022-28388   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-1199   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-29511   go-1.18.1
Medium   CVE-2021-29429   gradle-build-profile-6.9.2
Medium   CVE-2020-24550   find-0.1.1
Medium   CVE-2019-16370   gradle-build-cache-http-6.9.2
Medium   CVE-2021-39802   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-28389   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-1011   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-13844   g++-9-9.4.0-1ubuntu1~20.04.1
Medium   CVE-2022-23038   linux-libc-dev-5.4.0-109.123
Medium   CVE-2015-8553   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-23042   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-36222   libgssapi-krb5-2-1.17-6ubuntu4.1
Medium   CVE-2022-23041   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-39800   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-4159   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-13844   gcc-9-base-9.4.0-1ubuntu1~20.04.1
Medium   CVE-2022-1195   linux-libc-dev-5.4.0-109.123
Medium   CVE-2019-16370   gradle-build-cache-packaging-6.9.2
Medium   CVE-2021-36374   ant-launcher-1.10.9
Medium   CVE-2021-36222   libkrb5support0-1.17-6ubuntu4.1
Medium   CVE-2020-13844   libstdc++-9-dev-9.4.0-1ubuntu1~20.04.1
Medium   CVE-2022-23039   linux-libc-dev-5.4.0-109.123
Medium   CVE-2018-17977   linux-libc-dev-5.4.0-109.123
Medium   CVE-2019-16370   gradle-build-cache-6.9.2
Medium   CVE-2022-0644   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-29429   gradle-build-cache-6.9.2
Medium   CVE-2020-13844   cpp-9-9.4.0-1ubuntu1~20.04.1
Medium   CVE-2019-16370   gradle-build-events-6.9.2
Medium   CVE-2022-0998   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-28390   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-29429   gradle-build-events-6.9.2
Medium   CVE-2020-24504   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-9794   libsqlite3-0-3.31.1-4ubuntu0.2
Medium   CVE-2021-36373   ant-1.10.9
Medium   CVE-2013-7445   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-24958   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-39698   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-39686   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-13956   httpclient-2.8.3
Medium   CVE-2022-0382   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-4001   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-36373   ant-launcher-1.10.9
Medium   CVE-2022-0529   unzip-6.0-25ubuntu1
Medium   CVE-2021-29429   gradle-build-cache-packaging-6.9.2
Medium   CVE-2002-1647   slash-3.0.0
Medium   CVE-2021-3864   linux-libc-dev-5.4.0-109.123
Medium   GHSA-93q8-gq69-wqmw   ansi-regex-4.1.0
Medium   CVE-2020-16156   perl-modules-5.30-5.30.0-9ubuntu0.2
Medium   CVE-2005-0036   delegate-0.2.0
Medium   CVE-2020-13844   gcc-4:9.3.0-1ubuntu2
Medium   CVE-2021-20320   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-26966   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-3470   redis-4.0.6
Medium   CVE-2019-16370   gradle-build-operations-6.9.2
Medium   CVE-2019-16370   gradle-build-cache-base-6.9.2
Medium   CVE-2022-23037   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-26490   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-13844   libasan5-9.4.0-1ubuntu1~20.04.1
Medium   CVE-2020-17753   rc-1.2.8
Medium   CVE-2021-4160   openssl-3.0.0
Medium   CVE-2021-4150   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-28356   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-16156   libperl5.30-5.30.0-9ubuntu0.2
Medium   CVE-2021-33061   linux-libc-dev-5.4.0-109.123
Medium   CVE-2022-1204   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-12362   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-4148   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-36222   libk5crypto3-1.17-6ubuntu4.1
Medium   CVE-2021-29429   gradle-build-cache-http-6.9.2
Medium   CVE-2017-14197   matrix-0.4.2
Medium   GHSA-93q8-gq69-wqmw   ansi-regex-3.0.0
Medium   CVE-2021-4218   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-29429   gradle-build-cache-base-6.9.2
Medium   CVE-2021-29429   gradle-build-option-6.9.2
Medium   CVE-2022-0487   linux-libc-dev-5.4.0-109.123
Medium   GHSA-93q8-gq69-wqmw   ansi-regex-4.1.0
Medium   CVE-2022-23036   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-36222   libkrb5-3-1.17-6ubuntu4.1
Medium   CVE-2020-13844   libgcc-9-dev-9.4.0-1ubuntu1~20.04.1
Medium   CVE-2019-16370   gradle-build-init-6.9.2
Medium   CVE-2022-28893   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-27835   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-0707   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-32672   redis-4.0.6
Medium   CVE-2001-0381   openpgp-5.2.1
Medium   CVE-2021-45868   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-26932   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-4197   linux-libc-dev-5.4.0-109.123
Medium   CVE-2021-36374   ant-1.10.9
Medium   CVE-2002-1647   slash-3.0.0
Medium   CVE-2022-24448   linux-libc-dev-5.4.0-109.123
Medium   CVE-2020-16156   perl-5.30.0-9ubuntu0.2
Medium   CVE-2021-29429   gradle-build-operations-6.9.2
Negligible   CVE-2021-45261   patch-2.7.6-6
Negligible   CVE-2018-5709   libkrb5support0-1.17-6ubuntu4.1
Negligible   CVE-2021-32078   linux-libc-dev-5.4.0-109.123
Negligible   CVE-2017-13693   linux-libc-dev-5.4.0-109.123
Negligible   CVE-2017-13165   linux-libc-dev-5.4.0-109.123
Negligible   CVE-2018-20657   libctf-nobfd0-2.34-6ubuntu1.3
Negligible   CVE-2021-45078   binutils-common-2.34-6ubuntu1.3
Negligible   CVE-2018-6952   patch-2.7.6-6
Negligible   CVE-2021-36690   libsqlite3-0-3.31.1-4ubuntu0.2
Negligible   CVE-2021-45078   libctf0-2.34-6ubuntu1.3
Negligible   CVE-2018-5709   libkrb5-3-1.17-6ubuntu4.1
Negligible   CVE-2018-20657   binutils-common-2.34-6ubuntu1.3
Negligible   CVE-2020-14155   libpcre3-2:8.39-12build1
Negligible   CVE-2021-45078   binutils-2.34-6ubuntu1.3
Negligible   CVE-2021-45078   binutils-x86-64-linux-gnu-2.34-6ubuntu1.3
Negligible   CVE-2022-24959   linux-libc-dev-5.4.0-109.123
Negligible   CVE-2018-20657   binutils-x86-64-linux-gnu-2.34-6ubuntu1.3
Negligible   CVE-2018-12928   linux-libc-dev-5.4.0-109.123
Negligible   CVE-2018-20657   binutils-2.34-6ubuntu1.3
Negligible   CVE-2018-20657   libbinutils-2.34-6ubuntu1.3
Negligible   CVE-2021-26934   linux-libc-dev-5.4.0-109.123
Negligible   CVE-2019-16230   linux-libc-dev-5.4.0-109.123
Negligible   CVE-2018-20657   libctf0-2.34-6ubuntu1.3
Negligible   CVE-2018-5709   libk5crypto3-1.17-6ubuntu4.1
Negligible   CVE-2017-11164   libpcre3-2:8.39-12build1
Negligible   CVE-2018-5709   libgssapi-krb5-2-1.17-6ubuntu4.1
Negligible   CVE-2021-45078   libbinutils-2.34-6ubuntu1.3
Negligible   CVE-2021-45078   libctf-nobfd0-2.34-6ubuntu1.3

**Comment by rarkins** [comment]
@sveba the majority of your comment is off-topic for this issue. Please start a discussion in the main repo instead

**Comment by Konafets** [comment]
> Use the slim image with Docker socket mapped

@rarkins Do you have a pointer to the documentation how to do that?

**Comment by viceice** [comment]
👉 https://github.com/renovatebot/docker-renovate

See docs there

**Comment by viceice** [comment]
https://github.com/renovatebot/helm-charts/tree/main/charts/renovate supports docker on kubernetes

**Comment by Konafets** [comment]
We using Renovate Bot in Gitlab CI on gitlab.com. Currently I just have this `gitlab-ci.yaml`:

```yaml
image: 
  name: renovate/renovate

stages:
  - run

renovate:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_COMMIT_BRANCH == "main"'

  stage: run
  script:
    - renovate $RENOVATE_EXTRA_FLAGS

```

As the @Tofandel mentioned the usage of PHP7.4 avoids to automerge updates due to version conflict in `composer.json`. 

How can I use the slim container in combination with Gitlab CI?

**Comment by viceice** [comment]
https://gitlab.com/renovate-bot/renovate-runner

checkout our official gitlab runner template

**Comment by Konafets** [comment]
Sorry, I don't know how that helps me. Do you suggest to use the the renovate bot runner instead of `renovate/renovate`.

**Comment by viceice** [comment]
you don't need to, simply check the readme and templates hot to use docker mode on gitlab runner

**Comment by Konafets** [comment]
Thanks for the pointers but unfortunately I still do not have any glue where to start. Is it possible that I create my own image based on `renovate:slim` which includes Composer and PHP in recent versions?

P.S.: Whats the rationale to not update this image to latest PHP versions?

**Comment by viceice** [comment]
we will update soon

here a simple starter
https://github.com/renovatebot/docker-renovate/blob/main/docs/gitlab.md

**Comment by viceice** [comment]
will be updated tomorrow
